<?php

namespace AppBundle\Repository;

/**
 * SektorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SektorRepository extends \Doctrine\ORM\EntityRepository
{
}
